---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kubernetesupgraded-dimitrikoshkin-com-v1alpha1-machineimage
  failurePolicy: Fail
  name: mmachineimage.kb.io
  rules:
  - apiGroups:
    - kubernetesupgraded.dimitrikoshkin.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - machineimages
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kubernetesupgraded-dimitrikoshkin-com-v1alpha1-machineimage
  failurePolicy: Fail
  name: vmachineimage.kb.io
  rules:
  - apiGroups:
    - kubernetesupgraded.dimitrikoshkin.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - machineimages
  sideEffects: None
