---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kubernetesupgraded-dimitrikoshkin-com-v1alpha1-inclusterupgradeautomation
  failurePolicy: Fail
  name: minclusterupgradeautomation.kb.io
  rules:
  - apiGroups:
    - kubernetesupgraded.dimitrikoshkin.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - inclusterupgradeautomations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kubernetesupgraded-dimitrikoshkin-com-v1alpha1-ingitupgradeautomation
  failurePolicy: Fail
  name: mingitupgradeautomation.kb.io
  rules:
  - apiGroups:
    - kubernetesupgraded.dimitrikoshkin.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingitupgradeautomations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kubernetesupgraded-dimitrikoshkin-com-v1alpha1-machineimage
  failurePolicy: Fail
  name: mmachineimage.kb.io
  rules:
  - apiGroups:
    - kubernetesupgraded.dimitrikoshkin.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - machineimages
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kubernetesupgraded-dimitrikoshkin-com-v1alpha1-machineimagesyncer
  failurePolicy: Fail
  name: mmachineimagesyncer.kb.io
  rules:
  - apiGroups:
    - kubernetesupgraded.dimitrikoshkin.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - machineimagesyncers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kubernetesupgraded-dimitrikoshkin-com-v1alpha1-inclusterupgradeautomation
  failurePolicy: Fail
  name: vinclusterupgradeautomation.kb.io
  rules:
  - apiGroups:
    - kubernetesupgraded.dimitrikoshkin.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - inclusterupgradeautomations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kubernetesupgraded-dimitrikoshkin-com-v1alpha1-ingitupgradeautomation
  failurePolicy: Fail
  name: vingitupgradeautomation.kb.io
  rules:
  - apiGroups:
    - kubernetesupgraded.dimitrikoshkin.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingitupgradeautomations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kubernetesupgraded-dimitrikoshkin-com-v1alpha1-machineimage
  failurePolicy: Fail
  name: vmachineimage.kb.io
  rules:
  - apiGroups:
    - kubernetesupgraded.dimitrikoshkin.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - machineimages
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kubernetesupgraded-dimitrikoshkin-com-v1alpha1-machineimagesyncer
  failurePolicy: Fail
  name: vmachineimagesyncer.kb.io
  rules:
  - apiGroups:
    - kubernetesupgraded.dimitrikoshkin.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - machineimagesyncers
  sideEffects: None
