# permissions for end users to edit ingitupgradeautomations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ingitupgradeautomation-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubernetes-upgrader
    app.kubernetes.io/part-of: kubernetes-upgrader
    app.kubernetes.io/managed-by: kustomize
  name: ingitupgradeautomation-editor-role
rules:
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - ingitupgradeautomations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - ingitupgradeautomations/status
  verbs:
  - get
