# permissions for end users to view machineimagesyncers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: machineimagesyncer-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubernetes-upgrader
    app.kubernetes.io/part-of: kubernetes-upgrader
    app.kubernetes.io/managed-by: kustomize
  name: machineimagesyncer-viewer-role
rules:
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - machineimagesyncers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - machineimagesyncers/status
  verbs:
  - get
