---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - debianrepositorysources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - debianrepositorysources/finalizers
  verbs:
  - update
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - debianrepositorysources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - inclusterupgradeautomations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - inclusterupgradeautomations/finalizers
  verbs:
  - update
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - inclusterupgradeautomations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - ingitupgradeautomations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - ingitupgradeautomations/finalizers
  verbs:
  - update
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - ingitupgradeautomations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - machineimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - machineimages/finalizers
  verbs:
  - update
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - machineimages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - machineimagesyncers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - machineimagesyncers/finalizers
  verbs:
  - update
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - machineimagesyncers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - machineimagetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - plans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - plans/finalizers
  verbs:
  - update
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - plans/status
  verbs:
  - get
  - patch
  - update
