---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - kubernetesmachineimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - kubernetesmachineimages/finalizers
  verbs:
  - update
- apiGroups:
  - kubernetesupgraded.dimitrikoshkin.com
  resources:
  - kubernetesmachineimages/status
  verbs:
  - get
  - patch
  - update
