---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-annotator-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-annotator-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-annotator-rolebinding
subjects:
  - kind: ServiceAccount
    name: job-annotator-sa
    apiGroup: ""
roleRef:
  kind: Role
  name: job-annotator-role
  apiGroup: ""
---
apiVersion: kubernetesupgraded.dimitrikoshkin.com/v1alpha1
kind: Plan
metadata:
  labels:
    app.kubernetes.io/name: plan
    app.kubernetes.io/instance: plan-sample
    app.kubernetes.io/part-of: kubernetes-upgrader
    app.kubernetes.io/created-by: kubernetes-upgrader
  name: plan-sample
spec:
  versionRange: v1.27.x
  machineImageSelector:
    matchLabels:
      imageBuilderVersion: v1
---
apiVersion: kubernetesupgraded.dimitrikoshkin.com/v1alpha1
kind: ClusterClassClusterUpgrader
metadata:
  labels:
    app.kubernetes.io/name: clusterclassclusterupgrader
    app.kubernetes.io/instance: clusterclassclusterupgrader-sample
    app.kubernetes.io/part-of: kubernetes-upgrader
    app.kubernetes.io/created-by: kubernetes-upgrader
  name: clusterclassclusterupgrader-sample
spec:
  clusterName: capi-quickstart
  planRef:
    name: plan-sample
---
apiVersion: kubernetesupgraded.dimitrikoshkin.com/v1alpha1
kind: MachineImageTemplate
metadata:
  labels:
    app.kubernetes.io/name: machineimagetemplate
    app.kubernetes.io/instance: machineimagetemplate-sample
    app.kubernetes.io/part-of: kubernetes-upgrader
    app.kubernetes.io/created-by: kubernetes-upgrader
  name: machineimagetemplate-sample
spec:
  template:
    metadata:
      labels:
        imageBuilderVersion: v1
    spec:
      jobTemplate:
        spec:
          containers:
            - name: output-writer
              image: bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              command:
                - "/bin/bash"
                - "-o"
                - "xtrace" # Verbose output
                - "-o"
                - "errexit" # Exit on any error, except in a pipeline
                - "-c"
                - |
                  kubectl annotate job \
                    ${JOB_NAME} \
                    -n ${JOB_NAMESPACE} \
                    kubernetesupgraded.dimitrikoshkin.com/image-id="kindest/node:${KUBERNETES_VERSION}"
              env:
                - name: JOB_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['job-name']
                - name: JOB_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              volumeMounts:
                - name: output
                  mountPath: /tmp/output/
          serviceAccountName: job-annotator-sa
          volumes:
            - name: vsphere-vars
              secret:
                secretName: image-builder-vsphere-vars
            - name: output
              emptyDir: {}
          restartPolicy: Never
---
apiVersion: kubernetesupgraded.dimitrikoshkin.com/v1alpha1
kind: MachineImageSyncer
metadata:
  labels:
    app.kubernetes.io/name: machineimagesyncer
    app.kubernetes.io/instance: machineimagesyncer-sample
    app.kubernetes.io/part-of: kubernetes-upgrader
    app.kubernetes.io/created-by: kubernetes-upgrader
  name: machineimagesyncer-sample
spec:
  versionRange: v1.27.x
  machineImageTemplateRef:
    name: machineimagetemplate-sample
---
apiVersion: kubernetesupgraded.dimitrikoshkin.com/v1alpha1
kind: MachineImage
metadata:
  labels:
    app.kubernetes.io/name: machineimage
    app.kubernetes.io/instance: machineimage-sample
    app.kubernetes.io/part-of: kubernetes-upgrader
    app.kubernetes.io/created-by: kubernetes-upgrader
    imageBuilderVersion: v1
  name: machineimage-sample-1-28-1
spec:
  version: v1.28.1
  jobTemplate:
    spec:
      containers:
        - name: output-writer
          image: bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/bash"
            - "-o"
            - "xtrace" # Verbose output
            - "-o"
            - "errexit" # Exit on any error, except in a pipeline
            - "-c"
            - |
              kubectl annotate job \
                ${JOB_NAME} \
                -n ${JOB_NAMESPACE} \
                kubernetesupgraded.dimitrikoshkin.com/image-id="kindest/node:${KUBERNETES_VERSION}"
          env:
            - name: JOB_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['job-name']
            - name: JOB_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: output
              mountPath: /tmp/output/
      serviceAccountName: job-annotator-sa
      volumes:
        - name: vsphere-vars
          secret:
            secretName: image-builder-vsphere-vars
        - name: output
          emptyDir: {}
      restartPolicy: Never
---
apiVersion: kubernetesupgraded.dimitrikoshkin.com/v1alpha1
kind: MachineImage
metadata:
  labels:
    app.kubernetes.io/name: machineimage
    app.kubernetes.io/instance: machineimage-sample
    app.kubernetes.io/part-of: kubernetes-upgrader
    app.kubernetes.io/created-by: kubernetes-upgrader
    imageBuilderVersion: v0.1
  name: machineimage-sample-1-27-3
spec:
  version: v1.27.3
  jobTemplate:
    spec:
      containers:
        - name: output-writer
          image: bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/bash"
            - "-o"
            - "xtrace" # Verbose output
            - "-o"
            - "errexit" # Exit on any error, except in a pipeline
            - "-c"
            - |
              kubectl annotate job \
                ${JOB_NAME} \
                -n ${JOB_NAMESPACE} \
                kubernetesupgraded.dimitrikoshkin.com/image-id="kindest/node:${KUBERNETES_VERSION}"
          env:
            - name: JOB_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['job-name']
            - name: JOB_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: output
              mountPath: /tmp/output/
      serviceAccountName: job-annotator-sa
      volumes:
        - name: vsphere-vars
          secret:
            secretName: image-builder-vsphere-vars
        - name: output
          emptyDir: {}
      restartPolicy: Never
---
apiVersion: kubernetesupgraded.dimitrikoshkin.com/v1alpha1
kind: MachineImage
metadata:
  labels:
    app.kubernetes.io/name: machineimage
    app.kubernetes.io/instance: machineimage-sample
    app.kubernetes.io/part-of: kubernetes-upgrader
    app.kubernetes.io/created-by: kubernetes-upgrader
    imageBuilderVersion: v1
  name: machineimage-sample-1-27-2
spec:
  version: v1.27.2
  jobTemplate:
    spec:
      containers:
        - name: output-writer
          image: bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/bash"
            - "-o"
            - "xtrace" # Verbose output
            - "-o"
            - "errexit" # Exit on any error, except in a pipeline
            - "-c"
            - |
              kubectl annotate job \
                ${JOB_NAME} \
                -n ${JOB_NAMESPACE} \
                kubernetesupgraded.dimitrikoshkin.com/image-id="kindest/node:${KUBERNETES_VERSION}"
          env:
            - name: JOB_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['job-name']
            - name: JOB_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: output
              mountPath: /tmp/output/
      serviceAccountName: job-annotator-sa
      volumes:
        - name: vsphere-vars
          secret:
            secretName: image-builder-vsphere-vars
        - name: output
          emptyDir: {}
      restartPolicy: Never
---
apiVersion: kubernetesupgraded.dimitrikoshkin.com/v1alpha1
kind: MachineImage
metadata:
  labels:
    app.kubernetes.io/name: machineimage
    app.kubernetes.io/instance: machineimage-sample
    app.kubernetes.io/part-of: kubernetes-upgrader
    app.kubernetes.io/created-by: kubernetes-upgrader
    imageBuilderVersion: v1
  name: machineimage-sample-1-26-6
spec:
  version: v1.26.6
  jobTemplate:
    spec:
      containers:
        - name: output-writer
          image: bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/bash"
            - "-o"
            - "xtrace" # Verbose output
            - "-o"
            - "errexit" # Exit on any error, except in a pipeline
            - "-c"
            - |
              kubectl annotate job \
                ${JOB_NAME} \
                -n ${JOB_NAMESPACE} \
                kubernetesupgraded.dimitrikoshkin.com/image-id="kindest/node:${KUBERNETES_VERSION}"
          env:
            - name: JOB_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['job-name']
            - name: JOB_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: output
              mountPath: /tmp/output/
      serviceAccountName: job-annotator-sa
      volumes:
        - name: vsphere-vars
          secret:
            secretName: image-builder-vsphere-vars
        - name: output
          emptyDir: {}
      restartPolicy: Never
