# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/kubernetesupgraded.dimitrikoshkin.com_machineimages.yaml
- bases/kubernetesupgraded.dimitrikoshkin.com_plans.yaml
- bases/kubernetesupgraded.dimitrikoshkin.com_machineimagesyncers.yaml
- bases/kubernetesupgraded.dimitrikoshkin.com_machineimagetemplates.yaml
- bases/kubernetesupgraded.dimitrikoshkin.com_inclusterupgradeautomations.yaml
- bases/kubernetesupgraded.dimitrikoshkin.com_debianrepositorysources.yaml
- bases/kubernetesupgraded.dimitrikoshkin.com_ingitupgradeautomations.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- path: patches/webhook_in_machineimages.yaml
#- path: patches/webhook_in_plans.yaml
#- path: patches/webhook_in_machineimagesyncers.yaml
#- path: patches/webhook_in_machineimagetemplates.yaml
#- path: patches/webhook_in_inclusterupgradeautomations.yaml
#- path: patches/webhook_in_debianrepositorysources.yaml
#- path: patches/webhook_in_ingitupgradeautomations.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- path: patches/cainjection_in_machineimages.yaml
#- path: patches/cainjection_in_plans.yaml
#- path: patches/cainjection_in_machineimagesyncers.yaml
#- path: patches/cainjection_in_machineimagetemplates.yaml
#- path: patches/cainjection_in_inclusterupgradeautomations.yaml
#- path: patches/cainjection_in_debianrepositorysources.yaml
#- path: patches/cainjection_in_ingitupgradeautomations.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
